// src/components/icons/index.ts

/**
 * Angelisyn Website
 * Icons barrel exports.
 *
 * Centralized exports for Lucide React icons used throughout
 * the application. Import icons from this file instead of
 * directly from "lucide-react" to keep imports consistent.
 */

export {
    AlertCircle,
    ArrowRight,
    ArrowUpRight,
    BadgeCheck,
    Bell,
    BookOpen,
    Briefcase,
    Building2,
    Calendar,
    Check,
    CheckCheck,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    CircleHelp,
    Clock,
    Code2,
    Copy,
    Cpu,
    ExternalLink,
    Eye,
    FileText,
    Github,
    Globe,
    GraduationCap,
    Grid2x2,
    Hammer,
    HeartHandshake,
    Home,
    Info,
    Laptop,
    LayoutDashboard,
    LifeBuoy,
    Link,
    Linkedin,
    Loader2,
    Lock,
    Mail,
    MapPin,
    Menu,
    MessageCircle,
    Monitor,
    Moon,
    Network,
    Newspaper,
    Palette,
    Phone,
    Rocket,
    Search,
    Send,
    Server,
    Settings,
    Shield,
    ShieldCheck,
    Sparkles,
    Star,
    Sun,
    Target,
    Terminal,
    TrendingUp,
    Twitter,
    User,
    Users,
    X,
} from "lucide-react";